# testnet or mainnet
TestNet = true

# chain data directory
Data = "data"

# Logging switch
Logging = true

# P2P configuration
#Externale ip (default = "0.0.0.0")
ExternalIp = "0.0.0.0"

# Custom boot
#Boot = "/ip4/8.210.100.179/tcp/19100/ipfs/16Uiu2HAkv33SisCHpXE5ub4gxyRU5jCagAXCNoCPMUkQ82GYhC4i"

# P2P port (default = "19160")
P2PPort="19162"


# RPC configuration, (default = 19161)
RpcPort = "19163"
# RPC password
RpcPass = ""

# TLS switch
RpcTLS = false

# Roll back the node chain to a certain height, 0 means not roll back
RollBack = 0


# If it is a block generating node, it needs to be configured
# Json file address of the address private key
KeyFile = "../wallet/keystore/xC3LLtxiCaAcG2KrJmzo75pdavgqNLooz1N.json"
# Password to decrypt the private key json file
KeyPass = "1"

